// cofilmo-front/src/App.tsx
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import SideBar from "./components/sidebar/Sidebar";
import { Home } from "./pages/Home";
import { Add } from "./pages/Add";
import { Watch } from "./pages/Watch";
import { Random } from "./pages/Random";

const App = () => {
  return (
    <Router>
      <div className="w-full h-screen flex items-center bg-emerald-200 dark:bg-emerald-900">
        <SideBar />
        <Routes>
          <Route path="/" element={<Home/>}/>
          <Route path="/add" element={<Add/>}/>
          <Route path="/watch" element={<Watch/>}/>
          <Route path="/random" element={<Random/>}/>
        </Routes>
      </div>
    </Router>
  );
};

export default App;

// cofilmo-front/src/App.vue
<template>
  <main class="items-center justify-center h-screen flex grid-cols-2 bg-emerald-200 font-dosis dark:bg-emerald-900 transition-colors">
    <SideBar />
    <router-view />
  </main>
</template>

<script setup lang="ts">
import { onBeforeMount } from "vue";
import SideBar from "./components/SideBar.vue";
import { initializeDarkMode } from './utils/DarkMode.ts';

onBeforeMount(() => {
  initializeDarkMode();
});
</script>
