// cofilmo-front/src/components/SideBarHeader.vue
<template>
  <header class="relative">
    <div class="flex items-center py-2">
      <span class="min-w-[3.75rem] flex items-center">
        <img
          src="LogoCofilmo.png"
          alt="logo"
          class="w-14 h-14 rounded-lg"
          loading="lazy"
        />
      </span>

      <section
        class="text-xl font-medium flex flex-col text-emerald-700 dark:text-emerald-50"
      >
        <span class="text font-semibold" :class="{ hidden: props.closed }">Cofilmo</span>
        <span class="text font-medium" :class="{ hidden: props.closed }">Movie Tracker</span>
      </section>
    </div>
    <i
      class="bx bxs-right-arrow cursor-pointer absolute top-[50%] right-[-1.5rem] h-6 w-6 bg-emerald-700 flex items-center justify-center rounded-md text-lg text-emerald-200 translate-y-[-50%]"
      @click="handleClick"
    ></i>
  </header>
</template>

<script setup lang="ts">
import { defineProps, defineEmits } from "vue";

const props = defineProps({
  closed: Boolean
});

const emit = defineEmits(["toggleSidebar"]);

const handleClick = () => {
  emit("toggleSidebar");
};
</script>

<style>
.sidebar.close header .bxs-right-arrow {
  transform: translateY(-50%) rotate(180deg);
}

.sidebar header .bxs-right-arrow {
  transform: translateY(-50%);
}
</style>

// cofilmo-front/src/components/sidebar/SidebarHeader.tsx
import logo from "../../assets/LogoCofilmo.png";

interface ISidebarHeaderProps {
  toggle: boolean;
}

const SidebarHeader: React.FC<ISidebarHeaderProps> = ({ toggle }) => {
  return (
    <header
      className={`flex gap-4 items-center py-2 ${
        toggle
          ? "bg-none transition-all duration-200 delay-150"
          : "bg-emerald-100 rounded-xl p-2 dark:bg-emerald-800"
      }`}
    >
      <div className="min-w-[3rem] flex items-center">
        <img
          src={logo}
          alt="Cofilmo's logo"
          className="w-full h-full rounded-lg object-cover"
          loading="lazy"
        />
      </div>

      <section
        className={`${
          toggle
            ? "opacity-0 delay-100"
            : "flex flex-col text-xl font-nunito text-emerald-700 dark:text-emerald-50"
        }`}
      >
        <span className="font-semibold">Cofilmo</span>
        <span className="font-medium">Movie Tracker</span>
      </section>
    </header>
  );
};

export default SidebarHeader;
