// cofilmo-front/src/components/Sidebar.tsx
import { useState } from "react";
import SidebarHeader from "./SidebarHeader";
import SidebarMenu from "./SidebarMenu";
import ToggleSwitch from "./ToggleSwitch";

const Sidebar = () => {
  const [toggle, setToggle] = useState(false);
  return (
    <nav
      className={`${
        toggle ? "w-[4.5rem]" : ""
      } sidebar-container shadow-md shadow-stone-800 dark:shadow-stone-500 whitespace-nowrap rounded-md`}
    >
      <SidebarHeader toggle={toggle} />
      <SidebarMenu toggle={toggle} />
      <ToggleSwitch />
      <div
        className="absolute cursor-pointer top-[20%] h-6 w-6 bg-emerald-700 flex items-center justify-center rounded-md text-lg text-emerald-200 "
        onClick={() => {
          setToggle(!toggle);
        }}
      >
        <i
          className={`${
            toggle ? "rotate-180" : ""
          } bx bxs-right-arrow cursor-pointer text-lg text-emerald-200 transition-all duration-200`}
        />
      </div>
    </nav>
  );
};

export default Sidebar;

// cofilmo-front/src/components/SideBar.vue
<template>
  <nav
    class="sidebar fixed top-0 left-0 h-full bg-emerald-300 px-3 py-4 shadow-lg shadow-stone-800 dark:bg-emerald-950 dark:shadow-stone-500 whitespace-nowrap transition-all duration-[350ms]"
    :class="{ 'w-[6.8rem]': sidebarClosed, 'w-[15rem]': !sidebarClosed }">
    <SidebarHeader :closed="sidebarClosed" @toggleSidebar="toggleSidebar" />
    <SidebarMenu :closed="sidebarClosed" />
    <ToggleSwitch :darkMode="darkMode" @toggleDarkMode="toggleDarkMode" />
  </nav>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { darkMode, toggleDarkMode } from "../utils/DarkMode.ts";
import SidebarHeader from "./SideBarHeader.vue";
import SidebarMenu from "./SideBarMenu.vue";
import ToggleSwitch from "./ToggleSwitch.vue";

const sidebarClosed = ref(true);
const emit = defineEmits(['update:sidebarWidth']);

watch(sidebarClosed, (newVal) => {
  emit('update:sidebarWidth', newVal ? '6.8rem' : '15rem');
});

const toggleSidebar = () => {
  sidebarClosed.value = !sidebarClosed.value;
};
</script>

<style scoped>
/* On close sidebar */
.sidebar.close {
  width: 6.8rem;
}

.sidebar.close .text {
  opacity: 0;
  transition: opacity 0.2s ease-in-out;
}

.sidebar .text {
  opacity: 1;
  transition: opacity 0.2s ease-in-out;
}
</style>
